name: Build Project

on: # Vai ser executado quando
  push: # Quando realizar o push para branch main
    branches: ["main"]
  pull_request: # Quando for criado um pull request para branch main
    branches: ["main"]
  workflow_dispatch: # Para Iniciar o workflow de forma manual

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main #branch principal
          prefix: v #prefixo da versao no casao v1.0.0 exemplo
        
      - name: Tag the repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main' 
        #So vai ser criado a realese quando estiver sendo executado na branch principal, isto que o if faz

  backend-build-and-test:
    needs: versionamento #depende da conclusao do job de versionamento para ser executado
    runs-on: ubuntu-latest
    name: Backend Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Obtem sempre a ultima versao da tag 4
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: '8.x'
      
      - name: Restore
        run: |
          dotnet restore ./src/Todo.Api.sln
        
      - name: Build
        run: |
          dotnet build --no-restore ./src/Todo.Api.sln

      - name: Test
        run: |
            dotnet test ./src/Todo.Api.sln --no-restore --no-build --logger trx --results-directory "TestResults"          

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults #pasta onde se encontra os artefatos gerados

  frontend-build:
    if: false
    runs-on: ubuntu-latest
    name: Build Project 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Obtem sempre a ultima versao da tag 4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: '8.x'
        
      - name: Build and Test
        run: |
          dotnet restore ./src/Todo.Api.sln
          dotnet build --no-restore ./src/Todo.Api.sln
          dotnet test ./src/Todo.Api.sln --no-restore --no-build --logger trx --results-directory "TestResults" 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults #pasta onde se encontra os artefatos gerados  
      - name: Setup Node.Js
        uses: actions/setup-node@v4 # Obtem sempre a ultima versao da tag 4
        with:
          node-version: '20'
        
      - name: Install dependencies
        working-directory: ./src/web
        run: |
          npm install
          npm run build            